services:
  - type: web
    name: collaborative-taskflow-backend
    env: ruby
    plan: free
    buildCommand: cd backend && bundle install
    startCommand: cd backend && rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: collaborative-taskflow-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: collaborative-taskflow-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://collaborative-taskflow-backend.onrender.com

databases:
  - name: collaborative-taskflow-db
    databaseName: collaborative_taskflow
    user: collaborative_taskflow_user 